import { CircleAlert, FileSpreadsheet, Megaphone, Pause, Play, ShieldCheck } from "lucide-react";

import { requireActiveViewer } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { approveWaveReviewAction, createCampaignAction, importCampaignAction, releaseWaveAction, reviewWaveItemAction, transitionCampaignAction } from "./actions";
import styles from "./campaigns.module.css";

function importIssueText(errorCode: string | null) {
  if (errorCode === "already_in_campaign") return "Contato já incluído nesta campanha";
  return "Nome ausente/curto ou telefone inválido";
}

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ erro?: string; sucesso?: string }> }) {
  const viewer = await requireActiveViewer(); const feedback = await searchParams; const supabase = await createClient();
  const [{ data: campaigns }, { data: connections }, { data: contacts }, { data: imports }, { data: importIssues }, { data: waves }, { data: reviews }, { data: templates }] = await Promise.all([
    supabase.from("campaigns").select("*,whatsapp_connections(name,phone_e164,provider)").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}),
    supabase.from("whatsapp_connections").select("id,name,phone_e164,provider").eq("org_id",viewer.organization!.id).eq("status","active").eq("campaign_enabled",true),
    supabase.from("campaign_contacts").select("id,campaign_id,status,contacts(name)").eq("org_id",viewer.organization!.id),
    supabase.from("campaign_imports").select("id,campaign_id,total_rows,valid_rows,duplicate_rows,error_rows,status,created_at,mapping,file_sha256").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}),
    supabase.from("campaign_import_rows").select("import_id,row_number,status,error_code,normalized_name,normalized_phone").eq("org_id",viewer.organization!.id).in("status",["error","duplicate"]).order("row_number").limit(100),
    supabase.from("campaign_waves").select("id,campaign_id,wave_number,released_count,suppressed_count,status,released_at,review_status,review_required_count,review_completed_count,review_critical_count").eq("org_id",viewer.organization!.id).order("wave_number",{ascending:false}),
    supabase.from("campaign_wave_contact_reviews").select("id,campaign_id,wave_id,campaign_contact_id,outcome,notes,required_for_gate").eq("org_id",viewer.organization!.id).eq("required_for_gate",true),
    supabase.from("whatsapp_message_templates").select("id,connection_id,external_name,language").eq("org_id",viewer.organization!.id).eq("enabled",true).eq("purpose","campaign").eq("provider_status","APPROVED"),
  ]);
  return <div className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Reativação controlada</p><h1>Campanhas</h1><p>Importe, revise e libere ondas explícitas de 20, 50 e restante. Nada sai apenas por criar a campanha.</p></div><span className={styles.limit}><ShieldCheck size={16}/> até 500 contatos</span></header>
    {feedback.erro ? <p className={styles.error}>{feedback.erro}</p> : null}{feedback.sucesso ? <p className={styles.success}>{feedback.sucesso}</p> : null}
    {!connections?.length ? <p className={styles.warning}><CircleAlert size={16}/> Ative uma conexão WhatsApp e habilite “campanhas” antes de criar a primeira campanha.</p> : null}
    <div className={styles.layout}><main className={styles.list}>
      {campaigns?.map((campaign) => { const campaignContacts=(contacts??[]).filter((item)=>item.campaign_id===campaign.id); const stats=campaignContacts.reduce<Record<string,number>>((acc,item)=>{acc[item.status]=(acc[item.status]??0)+1;return acc;},{}); const contactNames=new Map(campaignContacts.map((item)=>[item.id,(item.contacts as {name:string}|null)?.name??"Contato"])); const latestImport=(imports??[]).find((item)=>item.campaign_id===campaign.id); const latestImportIssues=(importIssues??[]).filter((item)=>item.import_id===latestImport?.id); const campaignWaves=(waves??[]).filter((item)=>item.campaign_id===campaign.id); const latestWave=campaignWaves[0]; const waveReviews=(reviews??[]).filter((item)=>item.wave_id===latestWave?.id); const conn=campaign.whatsapp_connections as {name:string;phone_e164:string|null;provider:string}|null; const openingExamples=Array.isArray(campaign.opening_examples)?campaign.opening_examples.filter((item):item is string=>typeof item==="string"):[]; return <article className={styles.card} key={campaign.id}>
        <div className={styles.cardHeader}><span className={styles.icon}><Megaphone size={18}/></span><span><strong>{campaign.name}</strong><small>{conn?.name} · {conn?.phone_e164 ?? conn?.provider} · IA {campaign.ai_mode}</small></span><b data-status={campaign.status}>{campaign.status}</b></div>
        <div className={styles.metrics}><span><small>Prontos</small><strong>{stats.ready??0}</strong></span><span><small>Na fila</small><strong>{stats.queued??0}</strong></span><span><small>Suprimidos</small><strong>{stats.suppressed??0}</strong></span><span><small>Ondas</small><strong>{campaignWaves.length}</strong></span></div>
        {latestImport ? <p className={styles.importSummary}>Última base: {latestImport.valid_rows} válidos · {latestImport.duplicate_rows} duplicados · {latestImport.error_rows} erros · hash {latestImport.file_sha256?.slice(0,12)}…</p> : null}
        {latestImportIssues.length ? <details className={styles.importIssues}><summary>Ver linhas com erro ou duplicidade</summary><ul>{latestImportIssues.slice(0,10).map((item)=><li key={`${item.import_id}-${item.row_number}`}><strong>Linha {item.row_number+1}:</strong> {importIssueText(item.error_code)}{item.normalized_phone?` (${item.normalized_phone})`:""}</li>)}</ul></details> : null}
        {openingExamples.length ? <details className={styles.reviewPanel}><summary>Revisar exemplos de abertura</summary>{openingExamples.map((example,index)=><p key={`${campaign.id}-${index}`}>{example}</p>)}</details> : null}
        {latestWave ? <section className={styles.reviewPanel}><div className={styles.reviewHeader}><span><strong>Revisão da onda {latestWave.wave_number}</strong><small>{latestWave.review_completed_count}/{latestWave.review_required_count} aprovados · status {latestWave.review_status}</small></span>{latestWave.review_critical_count>0?<b>Campanha pausada por item crítico</b>:null}</div>{latestWave.review_status!=="approved"?<div className={styles.reviewList}>{waveReviews.map((review)=><form action={reviewWaveItemAction} className={styles.reviewItem} key={review.id}><input name="waveId" type="hidden" value={review.wave_id}/><input name="reviewId" type="hidden" value={review.id}/><span><strong>{contactNames.get(review.campaign_contact_id)??"Contato"}</strong><small>Resultado atual: {review.outcome}</small></span><select defaultValue={review.outcome==="pending"?"approved":review.outcome} name="outcome"><option value="approved">Aprovado</option><option value="needs_adjustment">Precisa de ajuste</option><option value="critical">Crítico</option></select><input defaultValue={review.notes??""} name="notes" placeholder="Nota obrigatória em ajuste/crítico"/><button>Salvar</button></form>)}</div>:null}{latestWave.review_status!=="approved"&&latestWave.review_completed_count===latestWave.review_required_count&&latestWave.review_critical_count===0?<form action={approveWaveReviewAction} className={styles.approveReview}><input name="waveId" type="hidden" value={latestWave.id}/><button>Aprovar revisão e liberar próxima onda</button></form>:null}</section>:null}
        {campaign.status==="draft"||campaign.status==="importing"||campaign.status==="review" ? <form action={importCampaignAction} className={styles.importForm}><input name="campaignId" type="hidden" value={campaign.id}/><label><span>Arquivo CSV</span><input accept=".csv,text/csv" name="csvFile" type="file"/><small>O telefone pode estar com máscara e DDD; adicionamos +55 automaticamente.</small></label><label><span>Ou cole o CSV</span><textarea name="csvText" placeholder={'cliente,celular\nMaria,(11) 99999-9999'} rows={3}/></label><label><span>Cabeçalho da coluna de nome (opcional)</span><input name="nameColumn" placeholder="Ex.: Nome" /></label><label><span>Cabeçalho da coluna de telefone (opcional)</span><input name="phoneColumn" placeholder="Ex.: Telefone principal" /><small>Deixe vazio para detectar automaticamente pela primeira linha.</small></label><button><FileSpreadsheet size={15}/> Mapear e processar base</button></form> : null}
        <div className={styles.actions}>
          {campaign.status==="review" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="approve"/><button>Aprovar campanha</button></form> : null}
          {(campaign.status==="approved"||campaign.status==="running") && campaignWaves.length<3 ? <form action={releaseWaveAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="count" type="hidden" value={campaignWaves.length===0?20:campaignWaves.length===1?50:500}/><button><Play size={14}/> Liberar {campaignWaves.length===0?"onda de 20":campaignWaves.length===1?"onda de 50":"restante"}</button></form> : null}
          {campaign.status==="running" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="pause"/><button className={styles.secondary}><Pause size={14}/> Pausar</button></form> : null}
          {campaign.status==="paused" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="resume"/><button><Play size={14}/> Retomar</button></form> : null}
        </div>
      </article>; })}
      {!campaigns?.length ? <section className={styles.empty}><Megaphone size={25}/><h2>Nenhuma campanha</h2><p>Conecte um número, declare a origem da base e crie um rascunho.</p></section> : null}
    </main><aside><form action={createCampaignAction} className={styles.createForm}><div><p className={styles.eyebrow}>Nova campanha</p><h2>Preparar reativação</h2></div><label><span>Nome</span><input name="name" required/></label><label><span>Conexão ativa</span><select name="connectionId" required><option value="">Selecione</option>{connections?.map((connection)=><option key={connection.id} value={connection.id}>{connection.name} · {connection.phone_e164??connection.provider}</option>)}</select></label><label><span>Template Meta aprovado</span><select name="messageTemplateId"><option value="">Não se aplica (Uazapi)</option>{templates?.map((template)=><option key={template.id} value={template.id}>{template.external_name} · {template.language}</option>)}</select></label><label><span>Modo do Pedro</span><select name="aiMode"><option value="off">Desligado</option><option value="shadow">Sombra</option><option value="assisted">Assistido</option><option value="production">Produção nesta campanha</option></select></label><label><span>Abertura</span><textarea name="openingTemplate" defaultValue="Olá {{name}}, tudo bem? Podemos retomar seu atendimento sobre imóveis?" rows={3}/></label><label><span>Declaração de consentimento</span><textarea name="consentStatement" defaultValue="Confirmo que esta base possui autorização válida para contato comercial via WhatsApp." rows={3}/></label><label><span>Origem da base</span><input name="consentSource" placeholder="CRM próprio, evento, formulário..."/></label><label className={styles.check}><input name="consentConfirmed" type="checkbox"/> Confirmo a declaração acima</label><button disabled={!connections?.length}>Criar rascunho</button></form></aside></div>
  </div>;
}
