import Link from "next/link";
import { Archive, CircleAlert, FileSpreadsheet, Megaphone, Pause, Pencil, Play, ShieldCheck } from "lucide-react";

import { requireActiveViewer } from "@/lib/auth/session";
import { belongsToCampaignView } from "@/lib/campaigns/view";
import { DEFAULT_CAMPAIGN_VARIANTS } from "@/lib/campaigns/message-variants";
import { createClient } from "@/lib/supabase/server";
import { createCampaignAction, editCampaignAction, importCampaignAction, releaseWaveAction, transitionCampaignAction } from "./actions";
import styles from "./campaigns.module.css";

function importIssueText(errorCode: string | null) {
  if (errorCode === "already_in_campaign") return "Contato já incluído nesta campanha";
  return "Nome ausente/curto ou telefone inválido";
}

export default async function CampaignsPage({ searchParams }: { searchParams: Promise<{ arquivadas?: string; erro?: string; sucesso?: string }> }) {
  const viewer = await requireActiveViewer(); const feedback = await searchParams; const supabase = await createClient();
  const showingArchived = feedback.arquivadas === "1";
  const campaignsQuery = supabase.from("campaigns").select("*,whatsapp_connections(name,phone_e164,provider)").eq("org_id",viewer.organization!.id);
  if (showingArchived) {
    campaignsQuery.eq("status", "archived").not("archived_at", "is", null);
  } else {
    campaignsQuery.neq("status", "archived").is("archived_at", null);
  }
  campaignsQuery.order("created_at",{ascending:false});
  const [{ data: campaigns }, { data: connections }, { data: contacts }, { data: imports }, { data: importIssues }, { data: waves }, { data: templates }] = await Promise.all([
    campaignsQuery,
    supabase.from("whatsapp_connections").select("id,name,phone_e164,provider").eq("org_id",viewer.organization!.id).eq("status","active").eq("campaign_enabled",true),
    supabase.from("campaign_contacts").select("id,campaign_id,status,contacts(name)").eq("org_id",viewer.organization!.id),
    supabase.from("campaign_imports").select("id,campaign_id,total_rows,valid_rows,duplicate_rows,error_rows,status,created_at,mapping,file_sha256").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}),
    supabase.from("campaign_import_rows").select("import_id,row_number,status,error_code,normalized_name,normalized_phone").eq("org_id",viewer.organization!.id).in("status",["error","duplicate"]).order("row_number").limit(100),
    supabase.from("campaign_waves").select("id,campaign_id,wave_number,released_count,suppressed_count,status,released_at").eq("org_id",viewer.organization!.id).order("wave_number",{ascending:false}),
    supabase.from("whatsapp_message_templates").select("id,connection_id,external_name,language").eq("org_id",viewer.organization!.id).eq("enabled",true).eq("purpose","campaign").eq("provider_status","APPROVED"),
  ]);
  return <div className={styles.page}>
    <header className={styles.header}><div><p className={styles.eyebrow}>Reativação controlada</p><h1>Campanhas</h1><p>Importe, revise e libere ondas explícitas de 20, 50 e restante. Nada sai apenas por criar a campanha.</p></div><div className={styles.headerTools}><span className={styles.limit}><ShieldCheck size={16}/> até 500 contatos</span><nav className={styles.viewTabs} aria-label="Visualização de campanhas"><Link className={!showingArchived ? styles.activeTab : undefined} href="/app/campanhas">Ativas</Link><Link className={showingArchived ? styles.activeTab : undefined} href="/app/campanhas?arquivadas=1"><Archive size={14}/> Arquivadas</Link></nav></div></header>
    {feedback.erro ? <p className={styles.error}>{feedback.erro}</p> : null}{feedback.sucesso ? <p className={styles.success}>{feedback.sucesso}</p> : null}
    {!connections?.length ? <p className={styles.warning}><CircleAlert size={16}/> Ative uma conexão WhatsApp e habilite “campanhas” antes de criar a primeira campanha.</p> : null}
    <div className={`${styles.layout} ${showingArchived ? styles.archivedLayout : ""}`}><main className={styles.list}>
      {(campaigns??[]).filter((campaign)=>belongsToCampaignView(campaign,showingArchived)).map((campaign) => { const campaignContacts=(contacts??[]).filter((item)=>item.campaign_id===campaign.id); const stats=campaignContacts.reduce<Record<string,number>>((acc,item)=>{acc[item.status]=(acc[item.status]??0)+1;return acc;},{}); const latestImport=(imports??[]).find((item)=>item.campaign_id===campaign.id); const latestImportIssues=(importIssues??[]).filter((item)=>item.import_id===latestImport?.id); const campaignWaves=(waves??[]).filter((item)=>item.campaign_id===campaign.id); const conn=campaign.whatsapp_connections as {name:string;phone_e164:string|null;provider:string}|null; const openingExamples=Array.isArray(campaign.opening_examples)?campaign.opening_examples.filter((item):item is string=>typeof item==="string"):[]; const canEdit=["draft","importing","review","approved"].includes(campaign.status)&&campaignWaves.length===0; return <article className={styles.card} key={campaign.id}>
        <div className={styles.cardHeader}><span className={styles.icon}><Megaphone size={18}/></span><span><strong>{campaign.name}</strong><small>{conn?.name} · {conn?.phone_e164 ?? conn?.provider} · IA {campaign.ai_mode}</small></span><b data-status={campaign.status}>{campaign.status}</b></div>
        {canEdit ? <details className={styles.reviewPanel}><summary><Pencil size={14}/> Editar configuração</summary><form action={editCampaignAction} className={styles.importForm}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><label><span>Nome</span><input defaultValue={campaign.name} name="name" required/></label><label><span>Conexão ativa</span><select defaultValue={campaign.connection_id} name="connectionId" required>{connections?.map((connection)=><option key={connection.id} value={connection.id}>{connection.name} · {connection.phone_e164??connection.provider}</option>)}</select></label><label><span>Template Meta aprovado</span><select defaultValue={campaign.message_template_id ?? ""} name="messageTemplateId"><option value="">Não se aplica (Uazapi)</option>{templates?.map((template)=><option key={template.id} value={template.id}>{template.external_name} · {template.language}</option>)}</select><small>Ao trocar conexão Meta, selecione também um template aprovado nela.</small></label><label><span>Modo do Pedro</span><select defaultValue={campaign.ai_mode} name="aiMode"><option value="off">Desligado</option><option value="shadow">Sombra</option><option value="assisted">Assistido</option><option value="production">Produção nesta campanha</option></select></label><label><span>Abertura</span><textarea defaultValue={campaign.opening_template} name="openingTemplate" required rows={3}/></label><button type="submit"><Pencil size={14}/> Salvar alterações</button></form></details> : null}
        <div className={styles.metrics}><span><small>Prontos</small><strong>{stats.ready??0}</strong></span><span><small>Na fila</small><strong>{stats.queued??0}</strong></span><span><small>Suprimidos</small><strong>{stats.suppressed??0}</strong></span><span><small>Ondas</small><strong>{campaignWaves.length}</strong></span></div>
        {latestImport ? <p className={styles.importSummary}>Última base: {latestImport.valid_rows} válidos · {latestImport.duplicate_rows} duplicados · {latestImport.error_rows} erros · hash {latestImport.file_sha256?.slice(0,12)}…</p> : null}
        {latestImportIssues.length ? <details className={styles.importIssues}><summary>Ver linhas com erro ou duplicidade</summary><ul>{latestImportIssues.slice(0,10).map((item)=><li key={`${item.import_id}-${item.row_number}`}><strong>Linha {item.row_number+1}:</strong> {importIssueText(item.error_code)}{item.normalized_phone?` (${item.normalized_phone})`:""}</li>)}</ul></details> : null}
        {openingExamples.length ? <details className={styles.reviewPanel}><summary>Revisar exemplos de abertura</summary>{openingExamples.map((example,index)=><p key={`${campaign.id}-${index}`}>{example}</p>)}</details> : null}
        {campaign.status==="draft"||campaign.status==="importing"||campaign.status==="review" ? <form action={importCampaignAction} className={styles.importForm}><input name="campaignId" type="hidden" value={campaign.id}/><label><span>Arquivo CSV</span><input accept=".csv,text/csv" name="csvFile" type="file"/><small>O telefone pode estar com máscara e DDD; adicionamos +55 automaticamente.</small></label><label><span>Ou cole o CSV</span><textarea name="csvText" placeholder={'cliente,celular\nMaria,(11) 99999-9999'} rows={3}/></label><label><span>Cabeçalho da coluna de nome (opcional)</span><input name="nameColumn" placeholder="Ex.: Nome" /></label><label><span>Cabeçalho da coluna de telefone (opcional)</span><input name="phoneColumn" placeholder="Ex.: Telefone principal" /><small>Deixe vazio para detectar automaticamente pela primeira linha.</small></label><button><FileSpreadsheet size={15}/> Mapear e processar base</button></form> : null}
        <div className={styles.actions}>
          {campaign.status==="review" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="approve"/><button>Aprovar campanha</button></form> : null}
          {(campaign.status==="approved"||campaign.status==="running") && campaignWaves.length<3 ? <form action={releaseWaveAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="count" type="hidden" value={campaignWaves.length===0?20:campaignWaves.length===1?50:500}/><button><Play size={14}/> Liberar {campaignWaves.length===0?"onda de 20":campaignWaves.length===1?"onda de 50":"restante"}</button></form> : null}
          {campaign.status==="running" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="pause"/><button className={styles.secondary}><Pause size={14}/> Pausar</button></form> : null}
          {campaign.status==="paused" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="resume"/><button><Play size={14}/> Retomar</button></form> : null}
          {campaign.status!=="archived" ? <form action={transitionCampaignAction}><input name="campaignId" type="hidden" value={campaign.id}/><input name="expectedVersion" type="hidden" value={campaign.version}/><input name="action" type="hidden" value="archive"/><button className={styles.secondary}><Archive size={14}/> Arquivar</button></form> : null}
        </div>
      </article>; })}
      {!(campaigns??[]).some((campaign)=>belongsToCampaignView(campaign,showingArchived)) ? <section className={styles.empty}><Megaphone size={25}/><h2>Nenhuma campanha</h2><p>{showingArchived ? "Nenhuma campanha arquivada." : "Conecte um número, declare a origem da base e crie um rascunho."}</p></section> : null}
    </main>{!showingArchived ? <aside><details className={styles.createCampaign} open={!campaigns?.length}><summary><Megaphone size={16}/><span><strong>Nova campanha</strong><small>Preparar uma reativação</small></span></summary><form action={createCampaignAction} className={styles.createForm}><div><p className={styles.eyebrow}>Nova campanha</p><h2>Preparar reativação</h2><small>As três variações perseguem o mesmo objetivo, mas usam aberturas diferentes e os dados da planilha. Respostas automáticas só são liberadas nesta campanha depois da configuração em Pedro &gt; Reativação de base.</small></div><label><span>Nome</span><input name="name" required/></label><label><span>Conexão ativa</span><select name="connectionId" required><option value="">Selecione</option>{connections?.map((connection)=><option key={connection.id} value={connection.id}>{connection.name} · {connection.phone_e164??connection.provider}</option>)}</select></label><label><span>Template Meta aprovado</span><select name="messageTemplateId"><option value="">Não se aplica (Uazapi)</option>{templates?.map((template)=><option key={template.id} value={template.id}>{template.external_name} · {template.language}</option>)}</select></label><label><span>Modo do Pedro</span><select name="aiMode"><option value="off">Desligado</option><option value="shadow">Sombra</option><option value="assisted">Assistido</option><option value="production">Produção nesta campanha</option></select></label>{DEFAULT_CAMPAIGN_VARIANTS.map((variant,index)=><label key={variant.id}><span>Variação {index+1}: {variant.label}</span><textarea name={`openingVariant${index+1}`} defaultValue={variant.template} rows={4}/><small>Use {"{{first_name}}"}, {"{{objetivo}}"}, {"{{entrada}}"}, {"{{parcela}}"}, {"{{orcamento}}"} e {"{{historico}}"}. Os valores vêm da planilha.</small></label>)}<label><span>Declaração de consentimento</span><textarea name="consentStatement" defaultValue="Confirmo que esta base possui autorização válida para contato comercial via WhatsApp." rows={3}/></label><label><span>Origem da base</span><input name="consentSource" placeholder="CRM próprio, evento, formulário..."/></label><label className={styles.check}><input name="consentConfirmed" type="checkbox"/> Confirmo a declaração acima</label><button disabled={!connections?.length}>Criar rascunho</button></form></details></aside> : null}</div>
  </div>;
}
