import { AlertTriangle, Bot, CalendarClock, Megaphone, RadioTower } from "lucide-react";
import { requireActiveViewer } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { claimEscalationAction, updateAlertAction } from "./actions";
import styles from "../operations.module.css";
import { PushSubscription } from "./push-subscription";

export default async function CentralPage({searchParams}:{searchParams:Promise<{erro?:string}>}){
  const viewer=await requireActiveViewer();const feedback=await searchParams;const supabase=await createClient();const operation=viewer.operations.find((item)=>item.is_default)??viewer.operations[0];
  const [{data:alerts},{data:escalations},{data:calls},{data:campaigns},{data:capacity},{data:health}]=await Promise.all([
    supabase.from("alerts").select("*").eq("org_id",viewer.organization!.id).neq("status","resolved").order("created_at",{ascending:false}).limit(30),
    supabase.from("escalations").select("*").eq("org_id",viewer.organization!.id).neq("status","resolved").order("created_at",{ascending:false}).limit(20),
    supabase.from("calls").select("id,status,starts_at,format").in("status",["awaiting_manager","unassigned_alerted","assigned"]).order("starts_at").limit(20),
    supabase.from("campaigns").select("id,name,status").in("status",["review","approved","running","paused"]).order("updated_at",{ascending:false}).limit(20),
    operation?supabase.from("operation_capacity").select("*").eq("operation_id",operation.id).maybeSingle():Promise.resolve({data:null}),
    supabase.from("integration_health_checks").select("component,status,checked_at,error_redacted").eq("org_id",viewer.organization!.id).order("checked_at",{ascending:false}).limit(20),
  ]);
  type HealthItem={component:string;status:string;checked_at:string;error_redacted:string|null};
  const latestHealth=Object.values((health??[]).reduce<Record<string,HealthItem>>((acc,item)=>{if(!acc[item.component])acc[item.component]=item;return acc;},{}));
  return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Central da operação</p><h1>O que precisa de atenção agora</h1><p>Alertas persistem até resolução; toast e WhatsApp nunca são a única cópia.</p><PushSubscription publicKey={process.env.NEXT_PUBLIC_WEB_PUSH_PUBLIC_KEY??""}/></div><span className={styles.badge}>{operation?.name??"Sem operação"}</span></header>{feedback.erro?<p className={styles.error}>A ação não pôde ser concluída.</p>:null}
    <section className={styles.metrics}><div className={styles.metric}><small>Alertas abertos</small><strong>{alerts?.length??0}</strong></div><div className={styles.metric}><small>Escaladas</small><strong>{escalations?.length??0}</strong></div><div className={styles.metric}><small>Capacidade ativa</small><strong>{capacity?.active_count??0}/30</strong></div><div className={styles.metric}><small>Proativo</small><strong>{capacity?.proactive_paused?"Pausado":"Ativo"}</strong></div></section>
    <div className={styles.grid}><section className={styles.panel}><div className={styles.panelHeader}><h2>Alertas</h2><span>acompanhar · ação · crítico</span></div><div className={styles.list}>{alerts?.map((alert)=><article className={`${styles.item} ${alert.severity==="critical"?styles.critical:alert.severity==="warning"?styles.warning:""}`} key={alert.id}><span><strong>{alert.title}</strong><small>{alert.body}</small><b>{alert.severity} · {alert.category}</b></span><div className={styles.actions}>{alert.status==="open"?<form action={updateAlertAction}><input name="alertId" type="hidden" value={alert.id}/><input name="status" type="hidden" value="acknowledged"/><button>Assumir</button></form>:null}<form action={updateAlertAction}><input name="alertId" type="hidden" value={alert.id}/><input name="status" type="hidden" value="resolved"/><button className={styles.secondary}>Resolver</button></form></div></article>)}{!alerts?.length?<p className={styles.empty}>Nenhum alerta aberto.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Escaladas do Pedro</h2><Bot size={17}/></div><div className={styles.list}>{escalations?.map((item)=><article className={styles.item} key={item.id}><span><strong>{item.category}</strong><small>{item.reason}</small><b>{item.severity} · {item.status}</b></span>{item.status==="open"?<form action={claimEscalationAction}><input name="escalationId" type="hidden" value={item.id}/><button>Assumir</button></form>:null}</article>)}{!escalations?.length?<p className={styles.empty}>Sem escaladas pendentes.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Calls em risco/próximas</h2><CalendarClock size={17}/></div><div className={styles.list}>{calls?.map((call)=><article className={styles.item} key={call.id}><span><strong>{new Date(call.starts_at).toLocaleString("pt-BR",{timeZone:operation?.timezone,dateStyle:"short",timeStyle:"short"})}</strong><small>{call.format}</small></span><b>{call.status}</b></article>)}{!calls?.length?<p className={styles.empty}>Nenhuma call visível.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Campanhas</h2><Megaphone size={17}/></div><div className={styles.list}>{campaigns?.map((campaign)=><article className={styles.item} key={campaign.id}><span><strong>{campaign.name}</strong><small>Ação depende do estado e dos gates de qualidade.</small></span><b>{campaign.status}</b></article>)}{!campaigns?.length?<p className={styles.empty}>Nenhuma campanha em operação.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Integrações</h2><RadioTower size={17}/></div><div className={styles.list}>{latestHealth.map((item)=><article className={styles.item} key={item.component}><span><strong>{item.component}</strong><small>{item.error_redacted??new Date(item.checked_at).toLocaleString("pt-BR")}</small></span><b>{item.status}</b></article>)}{!latestHealth.length?<p className={styles.empty}>Health checks ainda não executados.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Stop conditions</h2><AlertTriangle size={17}/></div><p className={styles.definition}>Pausa global, conexão down, modelo inseguro, opt-out acima do limite, call sem corretor e erro crítico de experimento exigem intervenção. A Central preserva a ocorrência até resolução explícita.</p></section></div>
  </div>;
}
