export const permissionOptions = [
  "settings.manage",
  "team.manage",
  "operations.manage",
  "operations.pause",
  "contacts.manage",
  "campaigns.manage",
  "pipeline.manage",
  "reports.view",
  "ai.manage",
  "finance.view",
  "privacy.manage",
  "exports.create",
  "checklists.manage",
] as const;
