import { FlaskConical, LockKeyhole } from "lucide-react";
import { requireActiveViewer } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { runSimulationAction } from "./actions";
import styles from "../operations.module.css";

export default async function SimulatorPage({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const viewer=await requireActiveViewer();const feedback=await searchParams;const supabase=await createClient();const{data:runs}=await supabase.from("simulator_runs").select("*,ai_executions(model_returned,latency_ms,estimated_cost,error_code)").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}).limit(30);
  return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Ambiente isolado</p><h1>Simulador</h1><p>Não envia WhatsApp, não agenda, não cria lead e não altera pipeline.</p></div><span className={styles.badge}><LockKeyhole size={13}/> sem efeitos externos</span></header>{feedback.erro?<p className={styles.notice}>A execução foi registrada como bloqueada: configure modelo ativo e chave BYOK para obter resposta real.</p>:null}{feedback.sucesso?<p className={styles.success}>Execução criada.</p>:null}
    <div className={styles.layout}><main className={styles.stack}><section className={styles.panel}><div className={styles.panelHeader}><h2>Histórico</h2><FlaskConical size={17}/></div><div className={styles.list}>{runs?.map((run)=>{const execution=run.ai_executions as {model_returned:string|null;latency_ms:number|null;estimated_cost:number|null;error_code:string|null}|null;return <article className={styles.item} key={run.id}><span><strong>{run.title}</strong><small>{run.simulated_input}</small><b>{run.status} · {execution?.model_returned??"sem modelo"}</b>{run.output_text?<p>{run.output_text}</p>:execution?.error_code?<small>{execution.error_code}</small>:null}</span></article>})}{!runs?.length?<p className={styles.empty}>Nenhuma simulação executada.</p>:null}</div></section></main><aside><form action={runSimulationAction} className={styles.formCard}><div><p className={styles.eyebrow}>Novo cenário</p><h2>Testar o Pedro</h2></div><label><span>Título</span><input name="title" required/></label><label><span>Mensagem simulada</span><textarea name="input" required rows={5}/></label><label><span>Estado inicial JSON</span><textarea className={styles.code} name="initialState" defaultValue={'{"qualification":{},"source":"simulator"}'} rows={6}/></label><button>Executar isoladamente</button></form></aside></div>
  </div>;
}
