import { BookMarked, GitCompareArrows } from "lucide-react";
import { requireActiveViewer } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { createLearningAction, reviewLearningAction } from "./actions";
import styles from "../operations.module.css";

export default async function LearningsPage({searchParams}:{searchParams:Promise<{erro?:string;sucesso?:string}>}){
  const viewer=await requireActiveViewer();const feedback=await searchParams;const supabase=await createClient();const[{data:suggestions},{data:cases},{data:runs}]=await Promise.all([
    supabase.from("learning_suggestions").select("*").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}),
    supabase.from("regression_cases").select("id,title,severity,source,active").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}).limit(30),
    supabase.from("regression_runs").select("id,status,total_cases,passed_cases,critical_failures,created_at").eq("org_id",viewer.organization!.id).order("created_at",{ascending:false}).limit(10),
  ]);
  return <div className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>Revisão humana obrigatória</p><h1>Aprendizados</h1><p>Aprovar cria rascunho e caso de regressão. Nenhuma observação altera o Pedro em produção sozinha.</p></div><span className={styles.badge}>{suggestions?.filter((item)=>["new","reviewing","conflict"].includes(item.status)).length??0} pendentes</span></header>{feedback.erro?<p className={styles.error}>A ação foi recusada pelas regras de aprendizado.</p>:null}{feedback.sucesso?<p className={styles.success}>Decisão registrada.</p>:null}
    <div className={styles.layout}><main className={styles.stack}><section className={styles.panel}><div className={styles.panelHeader}><h2>Fila de sugestões</h2><BookMarked size={17}/></div><div className={styles.list}>{suggestions?.map((item)=><article className={styles.item} key={item.id}><span><strong>{item.human_observation}</strong><small>{item.suggested_change}</small><b>{item.scope} · {item.status}</b>{item.conflict_details?<small>{item.conflict_details}</small>:null}</span>{["new","reviewing","conflict"].includes(item.status)?<div className={styles.actions}><form action={reviewLearningAction}><input name="suggestionId" type="hidden" value={item.id}/><input name="decision" type="hidden" value="approve_draft"/><button>Aprovar rascunho</button></form><form action={reviewLearningAction}><input name="suggestionId" type="hidden" value={item.id}/><input name="decision" type="hidden" value="mark_conflict"/><button className={styles.secondary}>Conflito</button></form><form action={reviewLearningAction}><input name="suggestionId" type="hidden" value={item.id}/><input name="decision" type="hidden" value="reject"/><button className={styles.secondary}>Rejeitar</button></form></div>:null}</article>)}{!suggestions?.length?<p className={styles.empty}>Nenhuma sugestão registrada.</p>:null}</div></section>
      <section className={styles.panel}><div className={styles.panelHeader}><h2>Regressões</h2><GitCompareArrows size={17}/></div><table className={styles.table}><thead><tr><th>Execução</th><th>Status</th><th>Casos</th><th>Críticos</th></tr></thead><tbody>{runs?.map((run)=><tr key={run.id}><td>{new Date(run.created_at).toLocaleString("pt-BR")}</td><td>{run.status}</td><td>{run.passed_cases}/{run.total_cases}</td><td>{run.critical_failures}</td></tr>)}</tbody></table><p className={styles.definition}>{cases?.length??0} casos ativos/registrados. Publicação continua separada na tela Pedro e depende de regressão.</p></section></main>
      <aside><form action={createLearningAction} className={styles.formCard}><div><p className={styles.eyebrow}>Observação manual</p><h2>Propor aprendizado</h2></div><label><span>Resposta observada</span><textarea name="observedResponse" rows={3}/></label><label><span>O que precisa melhorar</span><textarea name="observation" required rows={3}/></label><label><span>Mudança sugerida</span><textarea name="suggestedChange" required rows={4}/></label><label><span>Escopo</span><select name="scope"><option value="rule">Regra</option><option value="style">Estilo</option><option value="faq">FAQ</option><option value="qualification">Qualificação</option><option value="scheduling">Agendamento</option><option value="escalation">Escalada</option></select></label><button>Criar sugestão</button></form></aside></div>
  </div>;
}
